remote_theme: pmarsceill/just-the-docs
title: OpenAPI Documentation
description: For API designers and writers wishing formalize their API in an OpenAPI Description document.
baseurl: /documentation
logo: "/assets/images/OpenAPI_Logo_Pantone-1.png"
footer_content: "Copyright &copy; OpenAPI Initiative"
color_scheme: oai